service: aws-serverless-nodejs-ses-receive-email

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1


functions:
  incomingSesEmailParser:
    handler: handler.hello

  processAcceptOrReject:
    handler: handler.acceptReject

resources:
  Resources:
    SESPermissionToLambda:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: 
          "Fn::GetAtt": [ IncomingSesEmailParserLambdaFunction, Arn ]
        Principal: ses.amazonaws.com
        SourceAccount: 
          Ref: AWS::AccountId
    SESPermissionToInvokeProcessAcceptRejeectLambda:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: 
          "Fn::GetAtt": [ IncomingSesEmailParserLambdaFunction, Arn ]
        Principal: ses.amazonaws.com
        SourceAccount: 
          Ref: AWS::AccountId

